version: '3.9'

services:
    #catalog microservice
    catalogservice:
        build:
            context: './backend/src/CatalogService'
            dockerfile: './Api/Dockerfile'
        container_name: 'catalogservice'
        ports:
            - "5001:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings_DefaultConnection=${CATALOG_CONN_STR}
        depends_on:
            - sqldata_catalog

    #order microservice
    orderservice:
        build:
            context: './backend/src/OrderService'
            dockerfile: './Api/Dockerfile'
        container_name: 'orderservice'
        ports:
            - "5002:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings_DefaultConnection=${ORDER_CONN_STR}
        depends_on:
            - sqldata_order
 
    #user microservice
    userservice:
        build:
            context: './backend/src/UserService'
            dockerfile: './Api/Dockerfile'
        container_name: 'userservice'
        ports:
            - "5003:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings_DefaultConnection=${USER_CONN_STR}
        depends_on:
            - sqldata_user

    # SQL Server for Catalog
    sqldata_catalog:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqldata_catalog
        environment:
            SA_PASSWORD: ${SA_PASSWORD}
            ACCEPT_EULA: "Y"
        ports:
            - "14331:1433"
        volumes:
            - sqldata_catalog:/var/opt/mssql

    # SQL Server for Orders
    sqldata_order:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqldata_order
        environment:
            SA_PASSWORD: ${SA_PASSWORD}
            ACCEPT_EULA: "Y"
        ports:
            - "14332:1433"
        volumes:
            - sqldata_catalog:/var/opt/mssql

    # SQL Server for Users
    sqldata_user:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqldata_user
        environment:
            SA_PASSWORD: ${SA_PASSWORD}
            ACCEPT_EULA: "Y"
        ports:
            - "14334:1433"
        volumes:
            - sqldata_catalog:/var/opt/mssql

volumes:
    sqldata_catalog:
    sqldata_order:
    sqldata_user: